name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push images
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          
          docker buildx build --file client/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/social-app-frontend:latest --platform linux/amd64,linux/arm64 --push .
          docker buildx build --file server/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/social-app-backend:latest --platform linux/amd64,linux/arm64 --push .
          docker buildx build --file nginx/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/social-app-nginx:latest --platform linux/amd64,linux/arm64 --push .

          docker buildx build --file client/Dockerfile.dev --tag ${{ secrets.DOCKERHUB_USERNAME }}/social-app-frontend-dev:latest --platform linux/amd64,linux/arm64 --push .
          docker buildx build --file server/Dockerfile.dev --tag ${{ secrets.DOCKERHUB_USERNAME }}/social-app-backend-dev:latest --platform linux/amd64,linux/arm64 --push .

          docker buildx build --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/social-app-nginx-dev:latest --platform linux/amd64,linux/arm64 --push .
